# Generated by Django 2.1.2 on 2018-10-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181017_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_number', models.IntegerField(unique=True)),
                ('controller_model', models.CharField(choices=[('T8000', 'T8000'), ('T4000', 'T4000'), ('YM-ST4K', 'YM-ST4K'), ('YM-ST8K', 'YM-ST8K')], default='T8000', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='orders.Order')),
            ],
        ),
    ]
