# Generated by Django 2.1.2 on 2018-11-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='number_of_T8000',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
