# Generated by Django 2.1.2 on 2018-11-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181107_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controller',
            old_name='T8000s',
            new_name='T8000',
        ),
        migrations.AddField(
            model_name='controller',
            name='Buck_Converter_24v_to_12v',
            field=models.IntegerField(blank='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='Buck_Converter_24v_to_5v',
            field=models.IntegerField(blank='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='F16V3',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='F2_Raspberry_Pi',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='F4V3',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='Raspberry_Pi',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='T1000',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='T1000s',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='T4000',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='TP_Link',
            field=models.IntegerField(blank='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='Three_Twenty_24_Volt',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='Two_Forty_24_Volt',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
