# Generated by Django 2.1.3 on 2018-11-26 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20181126_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestampe', models.DateTimeField(auto_now_add=True)),
                ('for_controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='orders.Controller')),
            ],
        ),
    ]
