# Generated by Django 2.1.3 on 2018-11-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='for_controller',
        ),
        migrations.AddField(
            model_name='controller',
            name='controller_pictures',
            field=models.FileField(null=True, upload_to='controller_uploads/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
