# Generated by Django 2.1.3 on 2018-11-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20181127_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_image', models.ImageField(upload_to='controller_images/%Y/%m/%d')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_picture', to='orders.Controller')),
            ],
        ),
    ]
